// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"graphql-tutorial/src/graph/scalar"
)

type CreateTodoInput struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type CreateUserInput struct {
	Age       int32  `json:"age"`
	Country   string `json:"country"`
	Email     string `json:"email"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Role      string `json:"role"`
}

type GetUserInput struct {
	ID    *string `json:"id,omitempty"`
	Email *string `json:"email,omitempty"`
}

type IDInput struct {
	ID string `json:"id"`
}

type Mutation struct {
}

type Query struct {
}

type Todo struct {
	ID        string      `json:"id"`
	Completed bool        `json:"completed"`
	Started   bool        `json:"started"`
	Text      string      `json:"text"`
	UserId    scalar.Uint `json:"userId"`
	User      *User       `json:"user"`
	CreatedAt string      `json:"createdAt"`
	UpdatedAt string      `json:"updatedAt"`
}

type TodoResponse struct {
	Data    *Todo  `json:"data,omitempty"`
	Error   string `json:"error"`
	Success bool   `json:"success"`
}

type TodosResponse struct {
	Data    []*Todo `json:"data"`
	Error   string  `json:"error"`
	Success bool    `json:"success"`
}

type User struct {
	ID        string `json:"id"`
	Age       int32  `json:"age"`
	Country   string `json:"country"`
	Email     string `json:"email"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Role      string `json:"role"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type UserResponse struct {
	Data    *User  `json:"data,omitempty"`
	Error   string `json:"error"`
	Success bool   `json:"success"`
}

type UsersResponse struct {
	Data    []*User `json:"data"`
	Error   string  `json:"error"`
	Success bool    `json:"success"`
}
